services:
  app:
    build: .
    container_name: tech_challenge_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: tech_challenge_frontend
    ports:
      - "80:80"
    depends_on:
      - app

  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
